name: readme workflow
on:
  push:
    branches:
      - master
    paths-ignore:
      - 'README.md'
  workflow_dispatch:
jobs:
  readme-workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Updating GitHub Token
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB }}
        run: echo "GH_TOKEN=${GITHUB_TOKEN}" >> $GITHUB_ENV

      - name: checkout
        uses: actions/checkout@master
        with:
          fetch-depth: 0
          ref: master
          token: ${{ env.GH_TOKEN }}

      - name: 'Set up Python 3.7'
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: 'create readme'
        uses: 'clouddrove/github-actions@9.0.3'
        with:
          actions_subcommand: 'readme'
          github_token: '${{ secrets.GITHUB }}'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB }}

      - name: 'push readme'
        uses: 'clouddrove/github-actions@9.0.3'
        with:
          actions_subcommand: 'push'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB}}

      - name: 'Slack Notification'
        uses: clouddrove/action-slack@v2
        with:
          status: ${{ job.status }}
          fields: repo,author
          author_name: 'CloudDrove'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_TERRAFORM }}
        if: always()